name: Web CI Pipeline

on:
  push:
    paths:
      - clients/web/** 
      - .github/workflows/web.yml
    branches:
      - master
      - develop
    tags:
      - 'v*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Restore dependencies
        run: |
          cd clients/web
          npm ci

      - name: Build Angular app
        run: |
          cd clients/web
          npm run build -- --configuration production

#      - name: Run tests
#        run: |
#          cd clients/web
#          npm test -- --watch=false --code-coverage
  docker:
    needs: build
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        run: echo "${{ env.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ env.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_VERSION="latest"
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            IMAGE_VERSION=${GITHUB_REF#refs/tags/}
          fi
          docker buildx build \
            -t ${{ env.DOCKER_HUB_USERNAME }}/web:${IMAGE_VERSION} \
            -t ${{ env.DOCKER_HUB_USERNAME }}/web:latest \
            -f ./clients/web/Dockerfile \
            --build-arg ENVIRONMENT=Production \
            ./clients/web

      - name: Push latest Docker image to Docker Hub
        run: docker push ${{ env.DOCKER_HUB_USERNAME }}/web:latest

      - name: Push Docker image to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          IMAGE_VERSION=${GITHUB_REF#refs/tags/}
          docker push ${{ env.DOCKER_HUB_USERNAME }}/web:${IMAGE_VERSION}

